module.exports = {
  'noun': {
    'fox': -1,
    'dog': -1,
    'cat': -1,
    'horse': -1,
    'cow': -1,
    'tardigrade': -1,
    'baby': -1,
    'elder': -1,
    'giraffe': -1,
    'yak': -1,
    'octopus': -1,
    'rock': -1,
    'couch': -1,
    'loaf of bread': -1,
  },
  'adjective': {
    'quick': -1,
    'brown': -1,
    'lazy': -1,
    'pale': -1,
    'wacky': -1,
    'indescribable': -1,
    'nondescript': -1,
    'long-haired': -1,
  },
  'verb': {
    'fall asleep': -1,
    'jolt awake': -1,
    'flop over': -1,
    'think deeply': -1,
    'smile': -1,
  },
  'verbed': {
    'jumped over': -1,
    'slipped past': -1,
    'crept by': -1,
    'completely ignored': -1,
    'sniffed': -1,
    'talked to': -1,
    'became': -1,
  },
  'adverbly': {
    'immediately': -1,
    'violently': -1,
    'peacefully': -1,
    'freely': -1,
    'gracefully': -1,
    'clumsily': -1,
  },
}
